### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [dapphub/dappsys#57]
It would be really great if dappsys provided a contract implementation of a diamond.

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

**Comment by asymmetric** [comment]
![foo](https://user-images.githubusercontent.com/101816/85041691-d3c0ab80-b179-11ea-8781-f482f7fa0692.png)

Please don't spam our repos.

**Comment by mudgen** [comment]
@asymmetric I can certainly stop created issues like this on your repos,  but I did not "spam" your repos.  

Let's look at the definition of "spam".

> Irrelevant or inappropriate messages sent on the Internet to a large number of recipients.

I sent one message, which was unique and specifically written for your repo. I only sent one message to one of your repos.

My message was not irrelevant or inappropriate.  I am specifically interested in seeing a diamond building block from dappsys.
