### ISSUE TITLE
Modernize dappsys

### ISSUE THREAD

**Issue by TransmissionsDev** [dapphub/dappsys#58]
Many of the dappsys contracts are not compatible with the latest version of solidity. 

Even if they were, they could benefit from utilizing new features in the language/the more robust compiler (like in the case of overflow checks).

If these updates were made however, they would not be backwards compatible. I would argue that once `dapp` begins defaulting to using solc >0.8.0 (https://github.com/dapphub/dapptools/pull/580), it would be reasonable to make these upgrades to all the dappsys contracts instead of forking off a new modern version.

**Comment by MrChico** [comment]
There is an idea to substamtially reengineer dappsys, abandoning many components while keeping the ones that are still relevant, and move things to a monorepo. This is still in early stages, but sound a lot like what you are after

**Comment by TransmissionsDev** [comment]
> There is an idea to substamtially reengineer dappsys, abandoning many components while keeping the ones that are still relevant, and move things to a monorepo. This is still in early stages, but sound a lot like what you are after

Yeah that'd be great :)

**Comment by TransmissionsDev** [comment]
this is WIP now! https://github.com/dapp-org/dappsys-v2
